version: "3"

services:
  app:
    container_name: sensors_api
    build: ./
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensors
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./Backend:/go/src/project/
      - ./tools/:/tools
    working_dir: /go/src/project/
    ports:
      - 8081:8081
    depends_on:
      - db
    command: ["sh",  "/tools/compile.sh", "db"]

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensors
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./Backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306